coslr: false
criterions:
  PerformanceLoss:
    def_file: /glusterfs/whale/dataset/ILSVRC2012/classifier-balancing-master/loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: null
networks:
  classifier:
    def_file: /glusterfs/whale/dataset/ILSVRC2012/classifier-balancing-master/models/DotProductClassifier.py
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0002}
    params: {dataset: ImageNet_LT, feat_dim: 512, log_dir: /glusterfs/whale/dataset/ILSVRC2012/classifier-balancing-master/logs/ImageNet_LT/models/resnet10_uniform_cdbcetau1.5normsteplr_e120,
      num_classes: 1000, stage1_weights: false}
  feat_model:
    def_file: /glusterfs/whale/dataset/ILSVRC2012/classifier-balancing-master/models/ResNet10Feature.py
    fix: false
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0002}
    params: {dataset: ImageNet_LT, dropout: null, log_dir: /glusterfs/whale/dataset/ILSVRC2012/classifier-balancing-master/logs/ImageNet_LT/models/resnet10_uniform_cdbcetau1.5normsteplr_e120,
      stage1_weights: false, use_fc: false, use_selfatt: false}
shuffle: false
training_opt:
  backbone: resnet10
  batch_size: 512
  dataset: ImageNet_LT
  display_step: 10
  feature_dim: 512
  log_dir: /glusterfs/whale/dataset/ILSVRC2012/classifier-balancing-master/logs/ImageNet_LT/models/resnet10_uniform_cdbcetau1.5normsteplr_e120
  log_root: /glusterfs/whale/dataset/ILSVRC2012/classifier-balancing-master/logs/ImageNet_LT
  num_classes: 1000
  num_epochs: 120
  num_workers: 12
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 40}
  stage: resnet10_uniform_cdbcetau1.5normsteplr_e120
  sub_dir: models
